### ISSUE TITLE
Much improved solution for placing remotely drawn prefabs in CastAR Scene ( or Client side) 

### ISSUE THREAD

**Issue by romsondxr** [icywind/RemoteAssistantAR#12]
Hello @icywind 
I hope you are doing well.

Thanks for making this project available for all of us.

**Comment by Hisaack** [comment]
@romsondxr can you share your repo please?

**Comment by romsondxr** [comment]
> @romsondxr can you share your repo please?

No pal, I can't.
But try above steps, you will get much better results.

**Comment by Hisaack** [comment]
@romsondxr were you able to fix the problem of accuracy of the points where prefabs are instantiated? Like if you try to draw somewhere on top of the screen, the resulting points are not accurate..

**Comment by romsondxr** [comment]
> @romsondxr were you able to fix the problem of accuracy of the points where prefabs are instantiated? Like if you try to draw somewhere on top of the screen, the resulting points are not accurate..

Try the first comment on this thread, follow those steps, you will get much better results by placing prefabs in AR World space.

Trust me.

**Comment by icywind** [comment]
Hi, @romsondxr, I tried your suggestion but I couldn't achieve any better result. Your suggestion has been put into the dev-romsondxr branch of this repo.  The drawn dots couldn't even show in the right distance.  I also had some nasty configuration to fix when upgrading ARFoundation to 4.17, for building on Android.  Building on iOS is OK and that what I used for my tests.

Can you please make a Pull Request from your forked repo so we can get the exact change you have?

**Comment by Hisaack** [comment]
Yes, please make a pull request we see those changes that you've made @romsondxr

**Comment by romsondxr** [comment]
> Hi, @romsondxr, I tried your suggestion but I couldn't achieve any better result. Your suggestion has been put into the dev-romsondxr branch of this repo. The drawn dots couldn't even show in the right distance. I also had some nasty configuration to fix when upgrading ARFoundation to 4.17, for building on Android. Building on iOS is OK and that what I used for my tests.
> 
> Can you please make a Pull Request from your forked repo so we can get the exact change you have?

I can't make a pull request, because its company based project now, you can get in touch with me through LinkedIn.

**Comment by romsondxr** [comment]
> Yes, please make a pull request we see those changes that you've made @romsondxr

I can't make a pull request, because its company based project now, you can get in touch with me through LinkedIn.

**Comment by romsondxr** [comment]
> Hi, @romsondxr, I tried your suggestion but I couldn't achieve any better result. Your suggestion has been put into the dev-romsondxr branch of this repo. The drawn dots couldn't even show in the right distance. I also had some nasty configuration to fix when upgrading ARFoundation to 4.17, for building on Android. Building on iOS is OK and that what I used for my tests.
> 
> Can you please make a Pull Request from your forked repo so we can get the exact change you have?

I can't make a pull request, because its company based project now, you can get in touch with me through LinkedIn.(Would Like to discuss about the Raycasting method)

**Comment by Hisaack** [comment]
Couldn't you use this original repo to make a replicate and a separate project?

**Comment by Hisaack** [comment]
Hi @romsondxr I have tried the steps you gave but it doesn't work. Is there any step we need to reconfigure in order to achieve the stability?
