### ISSUE TITLE
Local video rendering failed and show blank screen

### ISSUE THREAD

**Issue by yalisandsoso** [icywind/RemoteAssistantAR#6]
I found a serious bug during the test. The specific test process is as follows.

1. Open the app （called it APP1） and click "Create", and then click "Join" with the other app (called it APP2) to connect them.

2. Click the "Back" arrow on the app.

3. Click the "Join" arrow on the APP1, you will find that the local video cannot be rendered to the designated area. In other words, you can only see a blank screen now.

In short, only one button  ("Create" or "Join") can be clicked in the same app. If you switch between "Join" and "Create", there will be problems.

I have made some changes on this issue, such as I modified the initialization code "mRtcEngine.SetExternalVideoSource(false, false)",  but I still have no way to fix it when using an external video source. I hope the author can fix this bug or provide suggestions for modification.

**Comment by Be90nia** [comment]
I also encountered this problem.When I click the Create button for the first time, the camera can be called normally, and then click the Join button after exiting, and a white screen will appear,camera will not turn on.
I hope the author can fix this bug or provide suggestions for modification.

**Comment by icywind** [comment]
The black screen is most likely you did not set up your App ID correctly. Many people had similar situation is found that their app is certificate enabled but the code never get the token assigned.  Please look at your account for your AppID.  You should start with an test appid without certificate option to run sample applications.
