### ISSUE TITLE
SendStreamMessage Fail

### ISSUE THREAD

**Issue by ARUtility** [icywind/RemoteAssistantAR#7]
For some reason when I try this demo the stream message does not get sent. I did some debugging and notice that SendStreamMessage fails with return value -2. I even tried hard coding values into the SendStreamMessage function and I always get the ERR_INVALID_ARGUMENT (2) error. 

Any ideas what may be causing this?

Thanks!

**Comment by icywind** [comment]
Were you able to obtain a positive value stream id?

**Comment by ARUtility** [comment]
The stream ID always returns 0.

**Comment by ARUtility** [comment]
I will add, I am able to send the datastream no problem with the old sdk and im successfully receiving the messages from the old sdk also. Even with a datastream id of 0. According to the docs any stream id greater than or equal to 0 is OK. I am curious why the demo code looks for a stream id > 0 and not greater than or equal to 0?

**Comment by icywind** [comment]
There maybe some problem with the SDK version you have.  Are you using 2.9.2.2 from the Asset Store?

**Comment by ARUtility** [comment]
I ended up downloading the SDK from the Agora website because Unity import kept failing without any error. Looks like the SDK on the site is 2.9.2. Maybe I can try to resolve the import issue in Unity and see if that fixes the problem?

It does look like the release date of 2.9.2.2 on the asset store is in April and the package on the Agora site i downloaded is February. Maybe the newer release will fix the issue. Is there a download link of 2.9.2.2 outside of the asset store in case it won't import again?

**Comment by icywind** [comment]
Hi there, please use this link to an archive of the SDK:  https://bit.ly/3fw59uZ
Also, if you like to get more help, feel free to join us on Slack: https://agoraiodev.slack.com/messages/unity-help-me
I will be interested to chat with you why there were downloading issues on Asset Store.
-Rick

**Comment by ARUtility** [comment]
@icywind you are my hero! The latest SDK fixed the issue 🤝🤜🤛. As far as why Unity import kept failing i am still not sure. Ive read a few posts where others have had this issue with other packages as well. I think its a unity bug.

Thank you for your quick help, it is greatly appreciated!
