### ISSUE TITLE
Channel is not connected

### ISSUE THREAD

**Issue by dragonxii2002** [icywind/RemoteAssistantAR#9]
I had followed the steps to install the SDK and the project contents in UNITY.

After Building, the two devices using "Create" and "Join" separately did not stream.

The two devices are iPhone and Android.  Do I need to run on the same platform as two devices?

Thanks.

**Comment by Hisaack** [comment]
It should run on any device @dragonxii2002 .
To make sure it is running both device, please confirm the audience touch watcher script that can be able to send the drawings from one device to another..

**Comment by dragonxii2002** [comment]
Thanks for your reply.
Sorry, I should make it clear, my problem is the "AudPlayScene" is not streaming with the "CastARScene", the AR Camera background is fine in "CastARScene".
The appID had been inserted in the AppID Field of 'Game Controller".
Is there anything I had missed?

**Comment by icywind** [comment]
HI 
@dragonxii2002 , is this your first Agora application to run? If yes, you probably should start with the SDK demo project and make sure that works for you. There are settings you must make to get streaming to work.  Please visit Agora.io and look at the FAQs if you have not get the basic setup working.

**Comment by dragonxii2002** [comment]
Hi @icywind,
Yes. I figured out what the problem is. Thanks for the following up.
